### ISSUE TITLE
How can I find "nvdla_vp_fpga_ami_ubuntu" AMI?

### ISSUE THREAD

**Issue by shgoupf** [nvdla/vp_awsfpga#1]
I tried to launch an AWS EC2 instance, but seems like there is no AMI named "nvdla_vp_fpga_ami_ubuntu" as suggested in the tutorial "http://nvdla.org/vp_fpga.html#using-the-virtual-simulator-on-nvidia-ami".

Anyone can help?

**Comment by HaiqingSun** [comment]
Hi Pengfei,

You can find the AMI with Instances->Launch Instance->Step 1: Choose an Amazon Machine Image (AMI)->Community AMIS
![image](https://user-images.githubusercontent.com/30793988/41387083-a14492f8-6fb7-11e8-87f7-7b2bdbacf026.png)

Best Regards,
Haiqing

**Comment by HaiqingSun** [comment]
BTW: Please set your AWS region to US East (N.Virginia) since each AWS region is independent.
![image](https://user-images.githubusercontent.com/30793988/41387353-131b3264-6fb9-11e8-9a86-8f1ac11f7567.png)

**Comment by shgoupf** [comment]
Thanks. After switching to US East (N.Virginia), I can find the AMI named "nvdla_vp_fpga_ami_ubuntu", :+1:

**Comment by shgoupf** [comment]
Issue resolved.
